export const genericAnalyzing = [
  "Analyzing your request…",
  "Processing your input…",
  "Reviewing context…",
  "Organizing details…",
  "Preparing your answer…",
  "Checking relevant points…",
  "Gathering information…",
  "Structuring a response…",
  "Lining up key facts…",
  "Finalizing notes…",
];

export const aiDocAnalyzing = [
  "Sequencing history timeline…",
  "Mapping symptom clusters…",
  "Reviewing objective findings…",
  "Checking differential checkpoints…",
  "Lining up workup priorities…",
  "Confirming safety guardrails…",
  "Bridging labs to symptoms…",
  "Organizing documentation steps…",
  "Preparing hand-off essentials…",
  "Noting next-visit prep…",
  "Aligning presentation details…",
  "Confirming onset and course…",
  "Reviewing prior assessments…",
  "Scanning exam highlights…",
  "Summarizing key intervals…",
  "Sorting pertinent positives…",
  "Sorting pertinent negatives…",
  "Pinpointing red-flag points…",
  "Grouping related complaints…",
  "Verifying medication lists…",
  "Reconciling allergies…",
  "Checking family history cues…",
  "Checking social history cues…",
  "Flagging follow-up needs…",
  "Finalizing AI Doc summary…",
];

export const clinicalAnalyzing = [
  "Reviewing clinical data…",
  "Checking vital sign trends…",
  "Scanning laboratory markers…",
  "Screening red-flag symptoms…",
  "Noting comorbidity overlaps…",
  "Reviewing medication interactions…",
  "Aligning staging criteria…",
  "Checking escalation thresholds…",
  "Mapping care pathways…",
  "Verifying triage indicators…",
  "Summarizing clinician notes…",
  "Cross-checking guideline cues…",
  "Reconciling problem list…",
  "Sorting acute vs chronic items…",
  "Highlighting abnormal values…",
  "Pairing symptoms with labs…",
  "Clarifying missing information…",
  "Prioritizing assessment items…",
  "Consolidating plan steps…",
  "Finalizing clinical outline…",
];

export const wellnessAnalyzing = [
  "Reviewing lifestyle anchors…",
  "Organizing daily routines…",
  "Checking sleep and energy notes…",
  "Mapping nutrition pivots…",
  "Lining up movement cues…",
  "Scanning stress patterns…",
  "Considering motivation hurdles…",
  "Gathering self-care signals…",
  "Highlighting mindset shifts…",
  "Noting support resources…",
  "Identifying easy wins…",
  "Prioritizing habit loops…",
  "Summarizing wellness focus…",
  "Finalizing practical tips…",
];

export const clinicalResearchAnalyzing = [
  "Correlating recent evidence…",
  "Scanning evolving guidelines…",
  "Reviewing meta-analysis signals…",
  "Summarizing RCT endpoints…",
  "Checking comparative effectiveness…",
  "Noting regulatory updates…",
  "Highlighting population outcomes…",
  "Reviewing quality-of-evidence notes…",
  "Identifying literature gaps…",
  "Aligning evidence with presentation…",
  "Cross-checking recommendations…",
  "Finalizing evidence-aware view…",
];

export const wellnessResearchAnalyzing = [
  "Reviewing health science findings…",
  "Scanning nutrition research…",
  "Checking exercise studies…",
  "Summarizing behavior research…",
  "Noting mindfulness evidence…",
  "Aligning outcomes with goals…",
  "Weighing practical implications…",
  "Finalizing research-aware tips…",
];
