export const FEATURES = {
  TRIALS_DEDUPE: true,
  TRIALS_GEO_ROUTING: true,
  TRIALS_PHASE_NORMALIZE: true,
  VACCINE_REMINDERS: true,
  MULTILINGUAL_HEALTH_EDU: true,
  RISK_SCORE_CALCULATORS: true,
  AI_HEALTH_COACH: true,
  RESEARCH_SUMMARIZER: true,
  DEVICE_GUIDES: true,
};
