export const runtime = "nodejs";
import { NextResponse } from "next/server";
import { getUserId } from "@/lib/getUserId";
import { buildProfileContext } from "@/lib/chat/profileContext";

export async function GET() {
  const userId = await getUserId();
  if (!userId) return new NextResponse("Unauthorized", { status: 401 });

  const ctx = await buildProfileContext(userId);

  // Build HTML report → convert to PDF-like format
  const html = `
<!DOCTYPE html>
<html>
<head><meta charset="utf-8"><title>Health Report</title>
<style>
  body { font-family: -apple-system, Inter, sans-serif; max-width: 700px; margin: 40px auto; color: #1a1a1a; padding: 0 20px; }
  h1 { color: #0694A2; border-bottom: 2px solid #06B6D4; padding-bottom: 8px; }
  h2 { color: #0694A2; margin-top: 24px; }
  .meta { color: #8E8E93; font-size: 13px; }
  .card { border: 1px solid #E5E5EA; border-radius: 12px; padding: 16px; margin: 12px 0; }
  .vital { display: inline-block; margin-right: 24px; }
  .vital-label { font-size: 12px; color: #8E8E93; }
  .vital-value { font-size: 20px; font-weight: 600; }
  .disclaimer { margin-top: 40px; padding: 16px; background: #F2F2F7; border-radius: 8px; font-size: 12px; color: #8E8E93; }
</style>
</head>
<body>
  <h1>Second Opinion \u2014 Health Report</h1>
  <p class="meta">Generated: ${new Date().toLocaleDateString("en-IN", { day: "numeric", month: "long", year: "numeric" })} | For: ${ctx.text.split("\n")[0]?.replace("[PATIENT CONTEXT]", "").trim() || "Patient"}</p>

  <h2>Patient Profile</h2>
  <div class="card">
    ${ctx.text ? ctx.text.split("\n").filter(Boolean).map(l => `<p>${l.replace("[PATIENT CONTEXT]", "")}</p>`).join("") : "<p>No profile data available</p>"}
  </div>

  <h2>Vitals</h2>
  <div class="card">
    ${ctx.vitals.bp_systolic ? `<div class="vital"><div class="vital-label">Blood Pressure</div><div class="vital-value">${ctx.vitals.bp_systolic}/${ctx.vitals.bp_diastolic} mmHg</div></div>` : ""}
    ${ctx.vitals.heart_rate ? `<div class="vital"><div class="vital-label">Heart Rate</div><div class="vital-value">${ctx.vitals.heart_rate} bpm</div></div>` : ""}
    ${ctx.vitals.bmi ? `<div class="vital"><div class="vital-label">BMI</div><div class="vital-value">${ctx.vitals.bmi}</div></div>` : ""}
    ${ctx.vitals.hba1c ? `<div class="vital"><div class="vital-label">HbA1c</div><div class="vital-value">${ctx.vitals.hba1c}%</div></div>` : ""}
    ${!Object.keys(ctx.vitals).length ? "<p>No vitals recorded</p>" : ""}
  </div>

  ${ctx.medications.length ? `<h2>Medications</h2><div class="card"><ul>${ctx.medications.map(m => `<li>${m}</li>`).join("")}</ul></div>` : ""}

  ${ctx.conditions.length ? `<h2>Conditions</h2><div class="card"><ul>${ctx.conditions.map(c => `<li>${c}</li>`).join("")}</ul></div>` : ""}

  <div class="disclaimer">
    <strong>Disclaimer:</strong> This report is generated by an AI health assistant for informational purposes only. It is NOT a substitute for professional medical advice, diagnosis, or treatment. Always consult a qualified healthcare provider.
  </div>
</body>
</html>`;

  return new NextResponse(html, {
    headers: {
      "Content-Type": "text/html; charset=utf-8",
      "Content-Disposition": `attachment; filename="health-report-${new Date().toISOString().split("T")[0]}.html"`,
    },
  });
}
